#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     intakeRoller,  tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     rightDrive,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     lift,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     leftDrive,     tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    latch,                tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    hopper,               tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    ir,                   tServoStandard)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

const int LATCH_UP = 220;
const int HOPPER_LOAD = 165;

void initializeRobot()
{
  return;
}

void driveUp() { //Drives slightly out of the parking zone to give room for the bot to turn
	motor[leftDrive] = -96;
	motor[rightDrive] = -96;

	wait1Msec(1000);	//TODO find real number

	motor[leftDrive] = 0;
	motor[rightDrive] = 0;
}

void turn() {	//Turns to block opposing bot
	motor[leftDrive] = 64;
	motor[rightDrive] = -64;

	wait1Msec(250);	//TODO find real number

	motor[leftDrive] = 0;
	motor[rightDrive] = 0;
}

void driveForward() { //Drives forward to blocking position
	motor[leftDrive] = -96;
	motor[rightDrive] = -96;

	wait1Msec(2000);	//TODO find real number

	motor[leftDrive] = 0;
	motor[rightDrive] = 0;
}

task main()
{
  initializeRobot();
  servo[hopper] = HOPPER_LOAD;
	servo[latch] = LATCH_UP;

  waitForStart(); // Wait for the beginning of autonomous phase.

  driveUp();
  turn();
  driveForward();

  while(true);	//Do nothing until game is done
}
